deploy:
  url: ''
key-vault:
  url: ''
digital-go-geocode:
  secret-name: ''
azure-translator:
  url: ''
  secret-name: ''
id:
  azure-storage:
    secret-name: ''
    container-name: ''
    blob-name: ''

